#!/usr/bin/env bash

queue_jar="bin/Queue-3.6/Queue.jar"

source "src/sh/bash_header"
source "src/sh/io_parser"

# parse table files 
pass_no="First"
if [[ "${input_table-}" ]]; then
    pass_no="Second"
fi

printf "[ %s: %s-pass covariation analysis ]\n" \
       "$(date)" "${pass_no}"

# make outdir
outdir="$(dirname "${output_table}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi
log_file="${outdir}/BaseRecalibrator.${pass_no}.log"
job_name="BaseRecalibrator_${pass_no}"

# build command
bam_files_arg="$(printf " -I %s " "${input_bam[@]}")"

cmd=( java -jar "${queue_jar}" -disableJobReport -jobRunner Drmaa
      -jobNative "-n 2 -J ${job_name}" -log "${log_file}"
      -S "src/scala/ScatterBaseRecalibrator.scala" 
      -R "${input_fa}" ${bam_files_arg}
      -L "${input_bed}"
      -knownSites "${input_vcf}"
      -out "${output_table}" -run )

if [[ "${pass_no}" == "Second" ]]; then
    printf "first_pass_table: %s\n" "${input_table}"
    cmd+=( "-BQSR" "${input_table}" )
fi

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run BaseRecalibrator
"${cmd[@]}" &

printf "[ %s: Waiting for BaseRecalibrator to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/BaseRecalibrator.${pass_no}.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    gatk-queue version,$(java -jar "${queue_jar}" --version 2>&1 | head -n 1)
    output,${outdir}
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
