#!/usr/bin/env bash

gatk="bin/GenomeAnalysisTK-3.6/GenomeAnalysisTK.jar"

printf "[ %s: Filter variants ]\n" "$(date)"

source "src/sh/bash_header"
source "src/sh/io_parser"

java_ram=$((max_cpus*3))"g"
mrir=$((ram_limit/6000)) # max records in RAM

# make outdir
outdir="$(dirname "${output_vcf}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi
log_file="${outdir}/VariantFiltration.log"

# GATK-recommended hard filter settings
fs='FS > 30.0'
qd='QD < 2.0'

# build command
cmd=( java "-Xmx${java_ram}" -jar "${gatk}" 
      -T VariantFiltration 
      --read_buffer_size "${mrir}" 
      -R "${input_fa}" -V "${input_vcf}" 
      -window 35 -cluster 3 
      -filterName FS -filter "${fs}"
      -filterName QD -filter "${qd}" 
      -o "${output_vcf}" )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run VariantFiltration
srun --ntasks=1 --cpus-per-task="${max_cpus}" \
    --output="${log_file}" "${cmd[@]}" &

printf "[ %s: Waiting for VariantFiltration to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/filter_variants.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    gatk version,$(java -jar ${gatk} --version 2>&1)
    output,${outdir}
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
