#!/usr/bin/env bash

gatk="bin/GenomeAnalysisTK-3.6/GenomeAnalysisTK.jar"

printf "[ %s: Select variants ]\n" "$(date)"

source "src/sh/bash_header"
source "src/sh/io_parser"

java_ram=$((max_cpus*3))"g"
mrir=$((ram_limit/6000)) # max records in RAM

# make outdir
outdir="$(dirname "${output_vcf}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi
log_file="${outdir}/SelectVariants.log"

# buld command
cmd=( java "-Xmx${java_ram}" -jar "${gatk}"
      -T SelectVariants
      --read_buffer_size "${mrir}" 
      -V "${input_vcf}" -R "${input_fa}"
      --excludeFiltered
      -o "${output_vcf}" )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run SelectVariants
srun --ntasks=1 --cpus-per-task="${max_cpus}" \
    --output="${log_file}" "${cmd[@]}" &

printf "[ %s: Waiting for SelectVariants to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/select_variants.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    gatk version,$(java -jar ${gatk} --version 2>&1)
    output,${outdir}
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
