#!/usr/bin/env bash

gatk="bin/GenomeAnalysisTK-3.6/GenomeAnalysisTK.jar"

printf "[ %s: Split variants by species ]\n" "$(date)"

source "src/sh/bash_header"
source "src/sh/io_parser"

java_ram=$((max_cpus*3))"g"
mrir=$((ram_limit/6000)) # max records in RAM
total_tasks="${#output_vcf[@]}"
cpus_per_task=$(( max_cpus /= total_tasks ))

# make outdir
outdir="$(dirname "${output_vcf}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# run one SelectVariants command per output_file
for species_file in "${output_vcf[@]}"; do
    species_prefix="$(basename "${species_file}" ".variants_filtered.vcf.gz")"
    log_file="${outdir}/${species_prefix}.SelectVariants.log"

    printf "\n  species_prefix: %s\n" "${species_prefix}"
    printf "        log_file: %s\n" "${log_file}"
    

    # build command
    cmd=( java "-Xmx${java_ram}" -jar "${gatk}" 
          -T SelectVariants
          --read_buffer_size "${mrir}" --num_threads "${cpus_per_task}"
          -R "${input_fa}" -V "${input_vcf}"
          -o "${species_file}"
          -sn "${species_prefix}"
          --excludeNonVariants --removeUnusedAlternates )

    shopt -s extglob
    printf "Final command line: "
    printf "%s " "${cmd[@]//+([[:blank:]])/ }"
    printf "\n"
    shopt -u extglob

    srun --ntasks=1 --cpus-per-task="${cpus_per_task}" --exclusive \
        --output="${log_file}" "${cmd[@]}" &
done

printf "[ %s: Waiting for SelectVariants to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/SelectVariants.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    gatk version,$(java -jar ${gatk} --version 2>&1)
    output,${outdir}
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
